### ISSUE TITLE
How to dismiss Button after popping up TVML view?

### ISSUE THREAD

**Issue by Wei-Xia** [toshi0383/TVMLKitchen#127]
Hello there,

I try to use **TVMLKitchen** last week. This is a really awesome tool to help with tvOS development.

I create a Button in a screen, after clicking the Button, another TVML will be pushed into screen. However, the Button is still in the screen, which is really annoying.

I don't know how to dismiss this button, anyone has any ideas? Thank you!

![simulator screen shot dec 7 2016 11 05 45](https://cloud.githubusercontent.com/assets/9309906/20975466/95d1f32e-bc6d-11e6-8743-20ddd421f6fd.png)

Here is my code for your reference.
```
class TestViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    @IBAction func test(sender: AnyObject!) {
        Kitchen.serve(xmlFile: "Oneup.xml")
    }
}
```

**Comment by toshi0383** [comment]
@Wei-Xia 
Hi, thanks for looking into this library!
The code looks okay. It's pretty much same as [Demo app's code here](https://github.com/toshi0383/TVMLKitchen/blob/master/SampleRecipe/ViewController.swift#L62-L64).

I'm guessing that you currently end up with multiple UIWindows. Do you have UIMainStoryboardFile in your Info.plist (#95) ? If so, possible solution is this.

```
        let appdelegateWindow = (UIApplication.shared.delegate as! AppDelegate).window!
        Kitchen.window.alpha = 1.0
        Kitchen.serve(
            xmlString: yourTVMLString,
            redirectWindow: appdelegateWindow,
            animatedWindowTransition: true
        )
```

This should take you back to the original window where you were at.

`Kitchen.serve(xmlFile:...)`  currently does not support multi UIWindow, so you might want to either 
1. Load your XML file as String manually
2. Create a PR to Add Multi Window Support for `serve(xmlFile:...)`

**Comment by toshi0383** [comment]
Multi UIWindow sample is available under NativeBaseSample directory. FYI.
https://github.com/toshi0383/TVMLKitchen/tree/master/NativeBaseSample

**Comment by Wei-Xia** [comment]
Hi @toshi0383 , thanks for your help!

Yes, I believe I have this multiple UIWindows issues. I followed your second comment to use **NativeBaseSample** instead, which performed very well! Thank you for solving this problem.

If I figure out how to add Multi Window Support for this library, I will definitely submit PR to you!
