### ISSUE TITLE
Search Recipe Grid option

### ISSUE THREAD

**Issue by anthonycastelli** [toshi0383/TVMLKitchen#65]
Could you add in a grid option for search results? Having it as a default option might be a better choice considering a search could return a large amount of data. A section just scrolls in a horizontal fashion.

**Comment by anthonycastelli** [comment]
Probably should of tried this first, but you can do what I was trying to achieve by creating a custom results template. 

```
<grid>
    <header>
        <title>{{TITLE}}</title>
    </header>

    <section id="Results">
        {{RESULTS}}
    </section>
</grid>
```

**Comment by toshi0383** [comment]
Yep, the result template callback is totally customisable. 😉
