### ISSUE TITLE
Presenting the tabBar from an Action

### ISSUE THREAD

**Issue by anthonycastelli** [toshi0383/TVMLKitchen#68]
Currently there isn't a way to present the TabBar via Kitchen.server() or via by giving KitchenTabBar a presentation style. Any chance of getting something like this implemented?

**Comment by toshi0383** [comment]
I take that as a feature request.😉
API should look like this, but we have to mark `KitchenTabBar.init(items:)` as public.

```
let tabbar = KitchenTabBar(items: [
    TabBar(), TabBar()
])
Kitchen.serve(recipe: tabbar)
```

Do you want to create a PR ?

**Comment by anthonycastelli** [comment]
Haha yeah, I wasn't sure how you wanted to go about it, but thats what I had in mind. I can do a PR. Coming right up!

**Comment by toshi0383** [comment]
Thanks for the PR !😄
