### ISSUE TITLE
How does Kitchen's default presentationType behave ?

### ISSUE THREAD

**Issue by toshi0383** [toshi0383/TVMLKitchen#75]
There are two push methods to present a TVML view,  replaceDocument and pushDocument.
https://developer.apple.com/library/tvos/documentation/TVMLJS/Reference/TVJSNavigationDocument_Ref/index.html

The `defaultPresenter` in kitchen.js **pushes** document. If loadingIndicator exists, it **replaces** document.

**Comment by toshi0383** [comment]
@anthonycastelli Would this answer your question in #69 ?

**Comment by anthonycastelli** [comment]
It does, however, if I present a TabBar and to to menu back to the previous screen, it'll just exit the app. So I think Its replacing it for me.

**Comment by toshi0383** [comment]
Could you modify the SampleRecipe demo code so it reproduces that problem ?
I can checkout the branch and see the problem quickly. 😉

**Comment by anthonycastelli** [comment]
Sure. I'll be home in about 30-40 minutes so I'll give it a whirl.

**Comment by anthonycastelli** [comment]
I was actually doing something wrong when I presenting the initial view. I kept presenting it Modaly and when I set it to Default, everything started working. :+1:

**Comment by toshi0383** [comment]
That sounds great 🙌
Case closed.🕵
