### ISSUE TITLE
How to load local files embedded in Template?

### ISSUE THREAD

**Issue by marbetschar** [toshi0383/TVMLKitchen#82]
How may I add local files (from the main bundle) to a xml template?

For example, I'd like to provide a static menu, the user can choose an item by using the stackTemplate.
For each menu Item I want to show a logo, served locally and stored in the main bundle.

For each entry I got a code similar to this:

```
<lockup>
    <img src="wordpress.png" width="548" height="274" />
        <title>WordPress</title>
</lockup>
```

And the image `wordpress.png` is stored in the main bundle - but as you can see on the following screenshot it isn't displayed:

![simulator screen shot 14 05 2016 17 44 13](https://cloud.githubusercontent.com/assets/392542/15269327/adbf5afe-19fb-11e6-938b-e2256606afa4.png)

**Comment by toshi0383** [comment]
Hi!

Added a new feature in #83 .
If you use `Kitchen.serve(xmlFile:)`, now you can do this.

```
<lockup>
    <img src="((MAIN_BUNDLE_URL))wordpress.png" width="548" height="274" />
        <title>WordPress</title>
</lockup>
```

If you use `Kitchen.serve(xmlString:)` instead, you need to manipulate xml string by yourself.
Checkout the code [here](https://github.com/toshi0383/TVMLKitchen/pull/83/files#diff-7bcc3225d1c9a98100711f31260a0fe4R22).

**Comment by marbetschar** [comment]
AWESOME!!!

How my I use this feature with Carthage?

**Comment by toshi0383** [comment]
If you want to try out quick, put `github "toshi0383/TVMLKitchen" "load-main-bundle-resource"` .
Otherwise I will merge it after CI passes and cut a new release for you. 😉

**Comment by toshi0383** [comment]
Shipped.

**Comment by toshi0383** [comment]
I'll leave `load-main-bundle-resource` branch for a while.

**Comment by marbetschar** [comment]
Awesome!! Thank you very much! I’ve already tested the load-main-bundle-resource, you can delete it whenever you like to!

mit sonnigen Grüssen

MARCO
kowalski

+41 44 341 8000
marco@mandelkind.swiss

MANDELKIND eG Schweiz
Bahnhofstrasse 100
CH-8001 Zürich

**Comment by toshi0383** [comment]
Anytime!
