### ISSUE TITLE
"Unsupported Architectures" when uploading to iTC

### ISSUE THREAD

**Issue by marbetschar** [toshi0383/TVMLKitchen#84]
I'm trying to upload my new & shiny tvOS app to iTunes Connect. But unfortunately I retrieve the following error on upload:

"Unsupported Architectures. The executable for ... TVMLKitchen.framework contains unsupported architectures '[x86_64]'".

I've downloaded & installed v0.7.1 with Carthage. Any Idea whats wrong?

**Comment by marbetschar** [comment]
As a workaround, this made an upload possible:
http://stackoverflow.com/questions/30547283/submit-to-app-store-issues

**Comment by toshi0383** [comment]
Discussion continued in #86 
Please feel free to reopen.
