### ISSUE TITLE
"Inalid Segment Alignment" when uploading to iTC

### ISSUE THREAD

**Issue by marbetschar** [toshi0383/TVMLKitchen#85]
When I'm trying to upload to iTunes Connect I got a "Inalid Segment Alignment" error:

"Inland Segment Alignment. The app binary at '....TVMLKitchen.framework/TVMLKitchen' does not have a proper segment alignment. Try rebuilding the app with the latest Xcode version."

I've downloaded & installed v0.7.1 using Carthage.

**Comment by marbetschar** [comment]
As a workaround, this made an upload possible:
http://stackoverflow.com/questions/30547283/submit-to-app-store-issues

**Comment by toshi0383** [comment]
Discussion continued in #86 
Please feel free to reopen.
