### ISSUE TITLE
"Position Independent Executable" when uploading to iTC

### ISSUE THREAD

**Issue by marbetschar** [toshi0383/TVMLKitchen#86]
When I'm trying to upload my app to iTunes Connect, I retrieve the following warning:

<img width="506" alt="bildschirmfoto 2016-05-14 um 20 46 15" src="https://cloud.githubusercontent.com/assets/392542/15270143/ef4fedd0-1a14-11e6-9f4e-905d5a1b42bc.png">

**Comment by marbetschar** [comment]
As a workaround, this made an upload possible:
http://stackoverflow.com/questions/30547283/submit-to-app-store-issues

**Comment by toshi0383** [comment]
Oh that's weird. I tried uploading before, but didn't have those issues.
Thanks for reporting!

**Comment by toshi0383** [comment]
@marbetschar 
I just tried uploading again recently and this error did not occur. Here is a checklist I came up with.
- Do you have `carthage copy-frameworks` Build Phase setup ?
- Is carthage up to date ?
- Did you change any "Hoge Paths" in Build Settings ?
- ~~Make sure ONLY_ACTIVE_ARCH = YES in your project's Release target.~~

This issue also could be related. TARGETED_DEVICE_FAMILY.
https://github.com/Carthage/Carthage/issues/873
