### ISSUE TITLE
LoadingRecipe is not public?

### ISSUE THREAD

**Issue by marbetschar** [toshi0383/TVMLKitchen#87]
I feel like the loading recipe should be public available?

https://github.com/toshi0383/TVMLKitchen/blob/swift2.2/Sources/Recipes/Loading.swift

**Comment by toshi0383** [comment]
Agree. You can create a PR 👍

**Comment by lukaskuster** [comment]
Just created one 😉 https://github.com/toshi0383/TVMLKitchen/pull/88

**Comment by toshi0383** [comment]
Thanks! Just merged.
