### ISSUE TITLE
.reloadTab Not Allowing for ActionID

### ISSUE THREAD

**Issue by mikehuebner** [toshi0383/TVMLKitchen#92]
Hey man!

Came across a small issue that I'm looking into now but simply put this:
`Kitchen.reloadTab(atIndex: 1, recipe: CatalogRecipe(title: self.title, movies: movies))`

prevents actionID's from within the XML to work. I'm trying to figure out why now. If you have any information on this that would be awesome!

Thanks!

**Comment by toshi0383** [comment]
Hey @mikehuebner .
Thanks for reporting.
Just submitted a patch !

**Comment by mikehuebner** [comment]
Thanks, I appreciate it. Curious what is was I couldn't figure out why the actionID wasn't getting picked up by the event handler.

Edit:
Ah, the actual DOM event listeners... 😅
